name: 'Troposphere launch/destroy env test'
on:
  push:
    branches:
      - master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  launch:
    name: 'Sceptre launch full environment troposphere'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Sceptre Validate'
        uses: Rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'validate prod'
          sceptre_troposphere: 'true'
          sceptre_troposphere_version: '2.6.0'
          sceptre_directory: './src/troposphere'

      - name: 'Sceptre launch'
        uses: Rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'launch -y prod'
          sceptre_troposphere: 'true'
          sceptre_troposphere_version: '2.6.0'
          sceptre_directory: './src/troposphere'

  delete:
    name: 'Sceptre delete full environment'
    runs-on: ubuntu-latest
    needs: launch
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Sceptre launch'
        uses: Rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'delete -y prod'
          sceptre_troposphere: 'true'
          sceptre_troposphere_version: '2.6.0'
          sceptre_directory: './src/troposphere'
