name: 'YAML launch/destroy stack test'
on:
  push:
    paths:
      - 'src/yaml'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  launch:
    name: 'Sceptre launch single stack'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Sceptre Validate'
        uses: rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'validate dev'
          sceptre_directory: './src/yaml'

      - name: 'Sceptre launch'
        uses: rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'launch -y dev'
          sceptre_directory: './src/yaml'
  delete:
    name: 'Sceptre delete full environment'
    runs-on: ubuntu-latest
    needs: launch
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Sceptre launch'
        uses: rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_subcommand: 'delete -y prod'
          sceptre_directory: './src/yaml'
