name: 'Sceptre validate yaml'
on:
  - pull_request
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  sceptre:
    name: 'Sceptre validate yaml'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'Sceptre Validate'
        uses: Rurquhart/sceptre-action@master
        with:
          sceptre_version: '2.3.0'
          sceptre_directory: "./src/yaml"
          sceptre_subcommand: 'validate dev'
